---
output: pdf_document
geometry: "left=1cm,right=1cm,top=2cm,bottom=2cm"
fontsize: 9pt
---
```{r include=FALSE, message=FALSE, warning=FALSE}
library("ez", quietly = TRUE)
library(lme4, quietly = TRUE)
library(xtable, quietly = TRUE)
library(stargazer, quietly = TRUE)
library(kableExtra, quietly = TRUE)
library(papeR, quietly = TRUE)
library(knitr, quietly = TRUE)
library(ggplot2, quietly = TRUE)
library(multcomp, quietly = TRUE)
library(sjPlot, quietly = TRUE)
library(sjstats, quietly = TRUE)
library(emmeans, quietly = TRUE)
require(lmerTest) # forces lmer to return p-values
options(width = 1800, show.signif.stars = TRUE) 
```
# NUMEROSITY ANALYSIS RESULTS
```{r, echo=TRUE, warning=FALSE, message=FALSE, fig.width=6, fig.height=3}
top_folder = '/Users/kohler/Dropbox/WRITING/Articles/2019_KohlerNumerositySSVEP/figures/results/experiment3'
counter = 0
for (c in c(5,6,8,9)) {
  for (q in c(1,2,3,4)) {
    cur_file = switch(q, "RLS_oddball_rc1_carr", "RLS_carrier_rc1_carr", "RLS_oddball_rc2_carr", "RLS_carrier_rc2_carr")
    cur_csv <- sprintf('%s/%s%d_full_projected_all_trials.csv', top_folder, cur_file, c)
    cur_data <-data.frame( read.csv(file = cur_csv ) )
    cur_data$cond <- factor(cur_data$condition, levels(cur_data$condition)[c(2,1)])
    cur_data$harm <- cur_data$harmonic
    cur_data$harm_alt <- factor(cur_data$harmonic, levels(cur_data$harmonic)[c(2,1,3,4)])
    g <- ggplot(cur_data, aes(harm, data, fill = cond)) +
      stat_summary(geom = "bar", fun.y = mean, position=position_dodge()) +
      stat_summary(geom = "errorbar", fun.data = mean_se, width=.3, position=position_dodge(.9))
    g <- g + theme(legend.title=element_blank(), 
      legend.justification=c(1,0), 
      legend.background = element_blank()) + 
      ggtitle(toupper(sprintf('%s%d\n',cur_file, c)))
    if (q == 1 && c == 6) {
      cat("RESULTS BELOW\n  ")
      cat("\n  ")
    }
    print(g)
    m1 <- lmer(data ~ cond * harm + (1|subject), cur_data)
    emm = emmeans(m1, ~ cond * harm, lmer.df = "satterthwaite")
    m2 <- lmer(data ~ cond + harm + (1|subject), cur_data)
    if (isSingular(m1)) {
      if (isSingular(m2)) {
        cat("WARNING: BOTH MODELS ARE SINGULAR!   ")
      } else {
        cat("WARNING: MODEL1 IS SINGULAR, BUT MODEL2 IS NOT!   ")
      }
    } else {
      cat("LOVELY: NONE OF THE MODELS ARE SINGULAR!   ")
    }
    if (!converge_ok(m1)) {
      if (!converge_ok(m2)) {
        cat("WARNING: BOTH MODELS DID NOT CONVERGE!\n\n")
      } else {
        cat("WARNING: MODEL1 DID NOT CONVERGE, BUT MODEL2 DID!\n\n")
      }
    } else {
      cat("LOVELY: BOTH MODELS CONVERGED!\n\n")
    }
    
    cat("ANOVA TEST FOR MAIN EFFECTS AND INTERACTIONS\n")
    print(anova(m1), type='pdf')
    cat("\nSUMMARY AND POST-HOC TESTS, harm1 baseline \n")
    print(prettify(summary(m1)), type='pdf')
    cat("\nESTIMATED MARGINAL MEANS, SIMPLE MAIN EFFECTS OF CONDITION WITHOUT CORRECTION\n")
    print(prettify(summary(pairs(emm, simple = "cond", adjust = "none"))))
    cat("\nTEST OF WHETHER OR NOT THE INTERACTION PROVIDES A BETTER FIT\n")
    print(anova(m1, m2))
  }
}
```
